apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app
  namespace: testapp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: test-app
  clusterIP: None
  type: ClusterIP